### ISSUE TITLE
Battery upgraded Leaf got stuck in fastcharger, chademo won't release

### ISSUE THREAD

**Issue by dalathegreat** [dalathegreat/BatteryUpgrade-UserManual#2]
Isolated event in Estonia, only one type of fastcharger, EFACEC branded one, caused this.
![image](https://user-images.githubusercontent.com/26695010/100065809-e92eb580-2e3c-11eb-8b40-0e65bf110718.png)

Vehicle that got stuck was an AZE0 30kWh -> 40kWh upgrade. This happened two times, one at ~85% SOC, other time at ~70%SOC. Current demand was 0A, no power flowing in the cable, but station did not stop. 

This happened with SW v2.25 and is potentially fixed with v2.32 SW that rewrote LB_PIN handling. If event doesn't happen again, we'll consider this one solved.

**Comment by luipir** [comment]
Without having any canbridge I had a similar lock with a chademos charger here in spain on my leaf 30kw 2016... No can log available to check if the problem was the car or the charger. I disconnected pushing red reset button of the charger. This to say that the problem can be outside your sw.

**Comment by dalathegreat** [comment]
Closing this issue as unable to reproduce, from over 300 users this was the only report and with early software version. If anyone is still affected by this, let me know (and update software first)
